version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: spotlyvf_db
    restart: always
    environment:
      MYSQL_DATABASE: spotlyvf
      MYSQL_ROOT_PASSWORD: KIOya100*
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: spotlyvf_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Django Backend
  backend:
    build: ./backend
    container_name: spotlyvf_backend
    restart: always
    volumes:
      - ./backend:/app
      - static_files:/app/staticfiles
      - media_files:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-)o#qsjb17r5ni^_xf#+7$3p6fm2(w+f7ec=s&z@=%$+zs^av*f
    depends_on:
      - db
      - redis
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Celery Worker
  celery:
    build: ./backend
    container_name: spotlyvf_celery
    restart: always
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-)o#qsjb17r5ni^_xf#+7$3p6fm2(w+f7ec=s&z@=%$+zs^av*f
    depends_on:
      - db
      - redis
    command: celery -A spotlyvf_backend worker --loglevel=info

volumes:
  mysql_data:
  redis_data:
  static_files:
  media_files:
