# Generated by Django 5.2.4 on 2025-07-14 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_place_id', models.CharField(blank=True, help_text='Google Places ID para lugares externos', max_length=200, null=True)),
                ('google_place_name', models.CharField(blank=True, help_text='Nombre del lugar de Google Places', max_length=200, null=True)),
                ('google_place_address', models.CharField(blank=True, help_text='Dirección del lugar de Google Places', max_length=500, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('visited_date', models.DateField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('business_response', models.TextField(blank=True, help_text='Respuesta del negocio a la reseña', null=True)),
                ('business_response_date', models.DateTimeField(blank=True, help_text='Fecha de la respuesta del negocio', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='googleplacesync',
            options={'ordering': ['-last_synced']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='placeclaim',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date', '-reservation_time']},
        ),
        migrations.RemoveIndex(
            model_name='googlereview',
            name='place_servi_google__4cbb78_idx',
        ),
        migrations.RemoveIndex(
            model_name='place',
            name='place_servi_average_52d240_idx',
        ),
        migrations.RenameField(
            model_name='googlereview',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='googlereview',
            old_name='author_name',
            new_name='place_name',
        ),
        migrations.RenameField(
            model_name='googlereview',
            old_name='created_at',
            new_name='scraped_at',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='is_open',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='placeclaim',
            old_name='user',
            new_name='claimant',
        ),
        migrations.RenameField(
            model_name='placeclaim',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='placeimage',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='placereview',
            old_name='text',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='placeclaim',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_description',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='business_hours',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='place',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='googleplacesync',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='googleplacesync',
            name='last_sync',
        ),
        migrations.RemoveField(
            model_name='googleplacesync',
            name='place',
        ),
        migrations.RemoveField(
            model_name='googleplacesync',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='googleplacesync',
            name='sync_errors',
        ),
        migrations.RemoveField(
            model_name='googleplacesync',
            name='sync_status',
        ),
        migrations.AlterUniqueTogether(
            name='googlereview',
            unique_together={('google_place_id', 'google_review_id')},
        ),
        migrations.RemoveField(
            model_name='place',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='place',
            name='google_maps_url',
        ),
        migrations.RemoveField(
            model_name='place',
            name='opening_hours',
        ),
        migrations.AlterUniqueTogether(
            name='placereview',
            unique_together={('place', 'user')},
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_registration',
            field=models.CharField(blank=True, default='', help_text='RUC o número de registro', max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('restaurant', 'Restaurante'), ('hotel', 'Hotel'), ('cafe', 'Café'), ('bar', 'Bar'), ('retail', 'Tienda'), ('service', 'Servicio'), ('entertainment', 'Entretenimiento'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Recibir notificaciones por email'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sms_notifications',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones por SMS'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='formatted_address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='google_photos',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='google_price_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='google_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='google_types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='google_user_ratings_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='last_synced',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default='', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='local_place',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_sync', to='place_service.place'),
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default='', max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleplacesync',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlereview',
            name='business_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='business_response_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Si Google marca al reviewer como verificado'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='reviewer_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='reviewer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlereview',
            name='reviewer_review_count',
            field=models.PositiveIntegerField(default=0, help_text='Número total de reseñas del usuario en Google'),
        ),
        migrations.AddField(
            model_name='googlereview',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='accepts_reservations',
            field=models.BooleanField(default=True, help_text='Si acepta reservas en línea'),
        ),
        migrations.AddField(
            model_name='place',
            name='auto_approve_reservations',
            field=models.BooleanField(default=False, help_text='Si las reservas se aprueban automáticamente'),
        ),
        migrations.AddField(
            model_name='place',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Email de contacto del negocio', max_length=254),
        ),
        migrations.AddField(
            model_name='place',
            name='business_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='place',
            name='business_name',
            field=models.CharField(blank=True, help_text='Nombre legal del negocio', max_length=200),
        ),
        migrations.AddField(
            model_name='place',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Teléfono principal del negocio', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='business_registration',
            field=models.CharField(blank=True, help_text='Número de registro o RUC', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando fue reclamado', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que reclamó este lugar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='place',
            name='cuisines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='is_claimed',
            field=models.BooleanField(default=False, help_text='Si un negocio ha reclamado este lugar'),
        ),
        migrations.AddField(
            model_name='place',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='max_advance_days',
            field=models.IntegerField(default=30, help_text='Días máximos de anticipación para reservas'),
        ),
        migrations.AddField(
            model_name='place',
            name='max_capacity',
            field=models.IntegerField(blank=True, help_text='Capacidad máxima del lugar', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='min_advance_hours',
            field=models.IntegerField(default=2, help_text='Horas mínimas de anticipación para reservas'),
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owned_places', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='tables_count',
            field=models.IntegerField(blank=True, help_text='Número de mesas (para restaurantes)', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notas del proceso de verificación'),
        ),
        migrations.AddField(
            model_name='place',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'No Verificado'), ('pending', 'Verificación Pendiente'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='placeclaim',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placeclaim',
            name='business_registration',
            field=models.CharField(default='', help_text='RUC, Cédula o número de registro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeclaim',
            name='claim_message',
            field=models.TextField(default='', help_text='Mensaje explicando por qué reclama este lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeclaim',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Place ID (para lugares de Google Places)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placereview',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de aprobación/rechazo', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Usuario del negocio que aprobó/rechazó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='assigned_table',
            field=models.CharField(blank=True, help_text='Mesa asignada por el restaurante', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='business_notes',
            field=models.TextField(blank=True, help_text='Notas internas del negocio'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se marcó como completada', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='estimated_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Place ID si la reserva es de un lugar de Google Places', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_show_at',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se marcó como no presentada', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Razón del rechazo si aplica'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='googleplacesync',
            name='google_place_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='googlereview',
            name='google_place_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='googlereview',
            name='google_review_id',
            field=models.CharField(help_text='ID único de la reseña en Google', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='googlereview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de personas que marcaron como útil'),
        ),
        migrations.AlterField(
            model_name='googlereview',
            name='rating',
            field=models.PositiveIntegerField(help_text='Rating de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='googlereview',
            name='review_date',
            field=models.DateTimeField(help_text='Fecha de la reseña en Google'),
        ),
        migrations.AlterField(
            model_name='place',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Places ID si proviene de Google Maps', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_range',
            field=models.CharField(choices=[('$', 'Budget'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], max_length=4),
        ),
        migrations.AlterField(
            model_name='place',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placeclaim',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notas del administrador durante la revisión'),
        ),
        migrations.AlterField(
            model_name='placeclaim',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Lugar local (para lugares ya en nuestra base de datos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='place_service.place'),
        ),
        migrations.AlterField(
            model_name='placeclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('under_review', 'En Revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='placeclaim',
            name='verification_documents',
            field=models.JSONField(default=list, help_text='URLs de documentos subidos para verificación'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='placereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='party_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Lugar interno vinculado (opcional si es Google Place no vinculado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='place_service.place'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Aprobación'), ('CONFIRMED', 'Confirmada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Completada'), ('NO_SHOW', 'No se presentó')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('place', 'reservation_date', 'reservation_time')},
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='place_servi_user_id_58d4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['place'], name='place_servi_place_i_47a25e_idx'),
        ),
        migrations.AddIndex(
            model_name='googleplacesync',
            index=models.Index(fields=['google_place_id'], name='place_servi_google__1e3198_idx'),
        ),
        migrations.AddIndex(
            model_name='googleplacesync',
            index=models.Index(fields=['latitude', 'longitude'], name='place_servi_latitud_30429d_idx'),
        ),
        migrations.AddIndex(
            model_name='googlereview',
            index=models.Index(fields=['google_place_id', 'review_date'], name='place_servi_google__24ba6b_idx'),
        ),
        migrations.AddIndex(
            model_name='googlereview',
            index=models.Index(fields=['scraped_at'], name='place_servi_scraped_d2cd49_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['city'], name='place_servi_city_0f5842_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['is_active'], name='place_servi_is_acti_bdc30f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user'], name='place_servi_user_id_5a61d6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['place'], name='place_servi_place_i_59d717_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_date'], name='place_servi_reserva_70599a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='place_servi_status_718e86_idx'),
        ),
        migrations.AddConstraint(
            model_name='placeclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False)), fields=('place', 'claimant'), name='unique_place_claimant'),
        ),
        migrations.AddConstraint(
            model_name='placeclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('google_place_id__isnull', False)), fields=('google_place_id', 'claimant'), name='unique_google_place_claimant'),
        ),
        migrations.AddField(
            model_name='reservationtimeslot',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='place_service.place'),
        ),
        migrations.AddField(
            model_name='review',
            name='business_responder',
            field=models.ForeignKey(blank=True, help_text='Usuario del negocio que respondió', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to='place_service.place'),
        ),
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='place_service.reservation'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='language',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='place',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='profile_photo_url',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='relative_time_description',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='text',
        ),
        migrations.RemoveField(
            model_name='googlereview',
            name='translated_text',
        ),
        migrations.RemoveField(
            model_name='placereview',
            name='photos',
        ),
        migrations.AlterUniqueTogether(
            name='reservationtimeslot',
            unique_together={('place', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['place', 'is_approved'], name='place_servi_place_i_c58002_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['google_place_id'], name='place_servi_google__941102_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='place_servi_user_id_c75cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='place_servi_rating_4c9da8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='place_servi_created_3904f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False)), fields=('user', 'place'), name='unique_user_place_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('google_place_id__isnull', False)), fields=('user', 'google_place_id'), name='unique_user_google_place_review'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('place__isnull', False), ('google_place_id__isnull', False), _connector='OR'), name='review_must_have_place_or_google_place'),
        ),
    ]
