# Generated by Django 5.2.4 on 2025-07-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_service', '0003_auto_20250714_1339'),
    ]

    operations = [
        migrations.RunSQL(
            # Agregar las columnas faltantes al modelo Review
            """
            ALTER TABLE place_service_review 
            ADD COLUMN is_featured TINYINT(1) DEFAULT 0,
            ADD COLUMN business_response LONGTEXT NULL,
            ADD COLUMN business_response_date DATETIME(6) NULL,
            ADD COLUMN business_responder_id BIGINT NULL,
            ADD CONSTRAINT fk_review_business_responder 
                FOREIGN KEY (business_responder_id) REFERENCES auth_users(id);
            """,
            reverse_sql="""
            ALTER TABLE place_service_review 
            DROP FOREIGN KEY fk_review_business_responder,
            DROP COLUMN business_responder_id,
            DROP COLUMN business_response_date,
            DROP COLUMN business_response,
            DROP COLUMN is_featured;
            """
        ),
    ]
