# Generated by Django 5.2.4 on 2025-07-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_service', '0004_auto_20250714_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='google_place_address',
            field=models.CharField(blank=True, help_text='Dirección del lugar de Google Places (solo para reservas de Google Places)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='google_place_name',
            field=models.CharField(blank=True, help_text='Nombre del lugar de Google Places (solo para reservas de Google Places)', max_length=200, null=True),
        ),
    ]
