# Generated by Django 5.2.4 on 2025-07-20 20:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place_service', '0005_reservation_google_place_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('total_reviews', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('positive_sentiment_count', models.IntegerField(default=0)),
                ('negative_sentiment_count', models.IntegerField(default=0)),
                ('sentiment_score', models.FloatField(default=0.5)),
                ('predicted_status', models.CharField(choices=[('successful', 'Negocio Exitoso'), ('recovering', 'En Recuperación'), ('at_risk', 'En Peligro'), ('uncertain', 'Incierto')], default='uncertain', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('last_analysis', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place_service.place')),
            ],
            options={
                'verbose_name': 'Business Analytics',
                'verbose_name_plural': 'Business Analytics',
                'db_table': 'business_analytics',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reviews_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('sentiment_ratio', models.FloatField(default=0.0)),
                ('rating_change', models.FloatField(default=0.0)),
                ('sentiment_change', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='analytics_service.businessanalytics')),
            ],
            options={
                'verbose_name': 'Analytics Trend',
                'verbose_name_plural': 'Analytics Trends',
                'db_table': 'analytics_trends',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=10)),
                ('category', models.CharField(choices=[('service', 'Atención al Cliente'), ('food_quality', 'Calidad de Comida'), ('pricing', 'Precios'), ('ambiance', 'Ambiente'), ('cleanliness', 'Limpieza'), ('marketing', 'Marketing'), ('operations', 'Operaciones')], max_length=20)),
                ('is_implemented', models.BooleanField(default=False)),
                ('implementation_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='analytics_service.businessanalytics')),
            ],
            options={
                'verbose_name': 'AI Recommendation',
                'verbose_name_plural': 'AI Recommendations',
                'db_table': 'ai_recommendations',
                'ordering': ['-priority', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment_label', models.CharField(max_length=10)),
                ('sentiment_score', models.FloatField()),
                ('key_aspects', models.JSONField(default=dict)),
                ('emotional_intensity', models.FloatField(default=0.0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment_prediction', to='place_service.review')),
            ],
            options={
                'verbose_name': 'Sentiment Prediction',
                'verbose_name_plural': 'Sentiment Predictions',
                'db_table': 'sentiment_predictions',
            },
        ),
        migrations.AddIndex(
            model_name='businessanalytics',
            index=models.Index(fields=['google_place_id'], name='business_an_google__b88702_idx'),
        ),
        migrations.AddIndex(
            model_name='businessanalytics',
            index=models.Index(fields=['predicted_status'], name='business_an_predict_7f16a8_idx'),
        ),
        migrations.AddIndex(
            model_name='businessanalytics',
            index=models.Index(fields=['last_analysis'], name='business_an_last_an_eab2b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticstrend',
            unique_together={('analytics', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='sentimentprediction',
            index=models.Index(fields=['sentiment_label'], name='sentiment_p_sentime_e0514d_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentprediction',
            index=models.Index(fields=['analyzed_at'], name='sentiment_p_analyze_f3061d_idx'),
        ),
    ]
